#!/bin/bash

CENIK_URL='http://m.tank-ono.cz/cz/index.php?page=cenik'

DESETINNY_ODDELOVAC='.'

CENA_BENZIN=$(curl -s $CENIK_URL | grep 'NATURAL 95' -A2 | grep divprice | cut -d '>' -f2- | cut -d '<' -f-2 | sed -e 's/<sup>/'$DESETINNY_ODDELOVAC'/' | tr -d '[:space:]')
CENA_DIESEL=$(curl -s $CENIK_URL | grep 'DIESEL' -A2 | grep divprice | cut -d '>' -f2- | cut -d '<' -f-2 | sed -e 's/<sup>/'$DESETINNY_ODDELOVAC'/' | tr -d '[:space:]')

echo $CENA_BENZIN
#echo $CENA_DIESEL

